general:
  # Общее количество повторений сообщений
  MESSAGE_REPEAT_COUNT: 3

  #Путь к текстовому документу с промтами
  TXT_PATH: "mj_gen.txt"

  # Режим запуска браузера: True для фонового режима, False для обычного
  HEADLESS_MODE: true

  #Время ожидание между запросами, время выберается рандомно по этому надо указать диапазон в секундах
  WAITING_TIME: [40, 50]

  # URL целевого канала в Discord
  TARGET_CHANNEL_URL: "https://discord.com/channels/id_chenel/id_group"

midjourney:
  # Соотношение сторон изображения (ширина:высота), например: '1:1', '4:3', '16:9'
  ar_value: "16:9"
  # Стиль генерации изображения
  style_value: "raw"
  # Качество рендеринга: 0.25 (низкое), 0.5 (среднее), 1 (стандартное), 2 (высокое)
  quality_value: 2
  # Уровень странности изображения: от 0 (без странностей) до 3000 (максимальная странность)
  weird_value: 0
  # Уровень хаоса: от 0 (предсказуемо) до 100 (максимальная вариативность)
  c_value: 25
  # Степень стилизации: от 0 (минимальная стилизация) до 1000 (и выше)
  s_value: 300
  # Версия алгоритма MidJourney
  v_value: "6.1"
  #Негативный промт
  negative_value: "text, watermark, logos"
